version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Python38.Dockerfile
    command: python3 nauta/train.py config_files/preprocessed.yaml
    # command: python3 nauta/dataset_generator.py config_files/preprocessing.yaml
    volumes:
      - ${HOME}/dataset/onc:/onc
    # stdin_open: true
    # tty: true
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
