method: maml
upload_results: true

hyperparameters:
  epochs: 40
  batch_size: 200
  episodes: 4
  n_shot: 5
  n_query: 15
  task_num: 4
  update_learning_rate: 0.01
  learning_rate: 0.001
  update_step: 5
  update_step_test: 10

paths:
  dataset_base_path: /home/dev/dataset

preprocessing:
  - name: mel
    channels: 1
  - name: cqt
    channels: 1
  - name: gammatone
    channels: 1
  - name: stft
    channels: 1
  - name: combined1
    channels: 3
  - name: combined2
    channels: 3
  - name: combined3
    channels: 3
  - name: combined4
    channels: 3

optimiser:
  type: sgd
  early_stop: 0

model:
  - name: original
  - name: vggnet
