hyperparameters:
  epochs: 40
  batch_size: 8
  learning_rate: 0.001
  lr_schd_gamma: 0.95
  sample_rate: 32000
  number_of_samples: 1

optim:
  type: "sgd"
  early_stop: 0

model:
  name: "cnncqt"
  cnn_depth: 0
  num_of_classes: 5
  input_channels: 1

paths:
  output_dir: "/results/out/inc2000_cnn_sgd_b8_mel"

dataset:
  type: "deepershipfeature"
  train_root_path: "/onc/preprocessed_interleaved/train/"
  validation_root_path: "/onc/preprocessed_interleaved/validation/"
  test_root_path: "/onc/preprocessed_interleaved/test/"
  preprocess:
    - "mel"

