hyperparameters:
  epochs: 40
  batch_size: 8
  learning_rate: 0.001
  lr_schd_gamma: 0.95
  sample_rate: 32000
  number_of_samples: 1

optim:
  type: "sgd"
  early_stop: 0

model:
  name: "resnet18"
  cnn_depth: 3
  num_of_classes: 6
  input_channels: 1

paths:
  output_dir: "./out/inc2000_resnet_sgd_b8_noback"

dataset:
  type: "deepershipfeature"
  train_root_path: "/home/thomas/Documents/Preprocessed/train/"
  validation_root_path: "/home/thomas/Documents/Preprocessed/validation/"
  test_root_path: "/home/thomas/Documents/Preprocessed/test/"
  preprocess:
    - mel

# dataset:
#   type: "deepershipfeature"
#   train_root_path: "/run/media/thomas/Elements/Preprocessed/train/"
#   validation_root_path: "/run/media/thomas/Elements/Preprocessed/validation/"
#   test_root_path: "/run/media/thomas/Elements/Preprocessed/test/"
#   preprocess:
#     - mel

preprocessing:
  type: "mel"
