hyperparameters:
  epochs: 40
  batch_size: 8
  learning_rate: 0.001
  lr_schd_gamma: 0.95

paths:
  dataset_base_path: /home/dev/dataset
  output_base_path: /home/dev/results

preprocessing:
  - mel
  - cqt
  - gammatone

optimiser:
  type: sgd
  early_stop: 0

model:
  - name: resnet18
    input_channels: 1
  - name: vggnet
    input_channels: 1

few_shot:
  way:
    - background
    - cargo
    - passengership
    - tanker
    - tug
  shot: 10
