hyperparameters:
  epochs: 50
  batch_size: 25
  learning_rate: 0.001
  lr_schd_gamma: 0.9
  sample_rate: 32000
  number_of_samples: 1

optim:
  type: "sgd"
  early_stop: 0

model:
  name: "resnet18"
  cnn_depth: 4
  num_of_classes: 4
  input_channels: 1

paths:
  output_dir: "/onc/out/inc2000_resnet_sgd_b25_noback"

dataset:
  type: "deepership"
  type: "test"
  train_metadata: "/onc/preprocessed/train/metadata.csv"
  validation_metadata: "/onc//preprocessed/validation/metadata.csv"
  test_metadata: "/onc//preprocessed/test/metadata.csv"
  preprocess:
    - mel

preprocessing:
  type: "mel"