hyperparameters:
  epochs: 50
  batch_size: 25
  learning_rate: 0.001
  lr_schd_gamma: 0.9
  sample_rate: 32000
  number_of_samples: 1

optim:
  type: "sgd"
  early_stop: 0

model:
  name: "resnet18"
  cnn_depth: 4
  num_of_classes: 5
  input_channels: 1

paths:
  output_dir: "./out/inc2000_resnet_sgd_b25_noback"

dataset:
  type: "deepership"
  train_metadata: "/run/media/thomas/Elements/Preprocessed/train/metadata_updated.csv"
  validation_metadata: "/run/media/thomas/Elements/Preprocessed/validation/metadata_updated.csv"
  test_metadata: "/run/media/thomas/Elements/Preprocessed/test/metadata_updated.csv"
  preprocess:
    - mel

# dataset:
#   type: "deepershipfeature"
#   train_root_path: "/run/media/thomas/Elements/Preprocessed/train/"
#   validation_root_path: "/run/media/thomas/Elements/Preprocessed/validation/"
#   test_root_path: "/run/media/thomas/Elements/Preprocessed/test/"
#   preprocess:
#     - mel

preprocessing:
  type: "mel"